global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['0.0.0.0:9090']

  - job_name: 'x-ui'
    static_configs:
      - targets: ['3xui_app:2053']
    metrics_path: '/metrics'
    scrape_interval: 30s
