name: Deploy Infrastructure with Ansible

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible
          ansible-galaxy collection install community.docker

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Run Ansible playbook
        run: |
          ansible-playbook -i ansible/inventory/production ansible/playbook.yml --private-key ~/.ssh/deploy_key
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
